name: dash-visualization
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - certifi=2020.11.8
  - decorator=4.4.2=py_0
  - ipdb=0.13.3=pyh9f0ad1d_0
  - ipython=7.19.0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.2
  - joblib=0.17.0=py_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libclang=10.0.1
  - liblapack=3.9.0=3_openblas
  - liblapacke=3.9.0=3_openblas
  - libopenblas=0.3.12
  - libopencv=4.4.0=py38_2
  - mysql-common=8.0.21=2
  - numpy=1.19.4
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.4.0=py38_2
  - pandas=1.0.5
  - parso=0.7.1=pyh9f0ad1d_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=7.2.0
  - pip=20.2.4=py_0
  - plotly=4.12.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8
  - ptyprocess=0.6.0=py_1001
  - py-opencv=4.4.0=py38h23f93f0_2
  - pygments=2.7.2=py_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - retrying=1.3.3=py_2
  - scikit-learn=0.23.2
  - setuptools=49.6.0
  - six=1.15.0=pyh9f0ad1d_0
  - threadpoolctl=2.1.0
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.35.1=pyh9f0ad1d_0
  - pip:
    - brotli==1.0.9
    - click==7.1.2
    - colorlover==0.3.0
    - cython==0.29.21
    - dash==1.16.3
    - dash-core-components==1.12.1
    - dash-html-components==1.1.1
    - dash-renderer==1.8.2
    - dash-table==4.10.1
    - flask==1.1.2
    - flask-compress==1.8.0
    - future==0.18.2
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - llvmlite==0.34.0
    - markupsafe==1.1.1
    - numba==0.51.2
    - scipy==1.5.4
    - tslearn==0.4.1
    - werkzeug==1.0.1